/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSyncRouteImport } from './routes/_app/sync'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthTwoFactorRouteImport } from './routes/_auth/two-factor'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AppContentCalendarRouteImport } from './routes/_app/content/calendar'
import { Route as AppContentPostsRouteImport } from './routes/_app/content/posts'
import { Route as AppContentQueueRouteImport } from './routes/_app/content/queue'
import { Route as AppInboxEngagementRouteImport } from './routes/_app/inbox/engagement'
import { Route as AppInboxMessagesRouteImport } from './routes/_app/inbox/messages'
import { Route as AppProfileAppearanceRouteImport } from './routes/_app/profile/appearance'
import { Route as AppProfileConnectionsRouteImport } from './routes/_app/profile/connections'
import { Route as AppProfileNotificationsRouteImport } from './routes/_app/profile/notifications'
import { Route as AppProfileSecurityRouteImport } from './routes/_app/profile/security'
import { Route as AppProfileSettingsRouteImport } from './routes/_app/profile/settings'
import { Route as AppWorkspaceApiKeysRouteImport } from './routes/_app/workspace/api-keys'
import { Route as AppWorkspaceMembersRouteImport } from './routes/_app/workspace/members'
import { Route as AppWorkspaceOverviewRouteImport } from './routes/_app/workspace/overview'
import { Route as AppWorkspaceSubscriptionRouteImport } from './routes/_app/workspace/subscription'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSyncRoute = AppSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AppContentCalendarRoute = AppContentCalendarRouteImport.update({
  id: '/content/calendar',
  path: '/content/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppContentPostsRoute = AppContentPostsRouteImport.update({
  id: '/content/posts',
  path: '/content/posts',
  getParentRoute: () => AppRoute,
} as any)
const AppContentQueueRoute = AppContentQueueRouteImport.update({
  id: '/content/queue',
  path: '/content/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxEngagementRoute = AppInboxEngagementRouteImport.update({
  id: '/inbox/engagement',
  path: '/inbox/engagement',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxMessagesRoute = AppInboxMessagesRouteImport.update({
  id: '/inbox/messages',
  path: '/inbox/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileAppearanceRoute = AppProfileAppearanceRouteImport.update({
  id: '/profile/appearance',
  path: '/profile/appearance',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileConnectionsRoute = AppProfileConnectionsRouteImport.update({
  id: '/profile/connections',
  path: '/profile/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileNotificationsRoute = AppProfileNotificationsRouteImport.update({
  id: '/profile/notifications',
  path: '/profile/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileSecurityRoute = AppProfileSecurityRouteImport.update({
  id: '/profile/security',
  path: '/profile/security',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileSettingsRoute = AppProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceApiKeysRoute = AppWorkspaceApiKeysRouteImport.update({
  id: '/workspace/api-keys',
  path: '/workspace/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceMembersRoute = AppWorkspaceMembersRouteImport.update({
  id: '/workspace/members',
  path: '/workspace/members',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceOverviewRoute = AppWorkspaceOverviewRouteImport.update({
  id: '/workspace/overview',
  path: '/workspace/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceSubscriptionRoute =
  AppWorkspaceSubscriptionRouteImport.update({
    id: '/workspace/subscription',
    path: '/workspace/subscription',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AppAccountsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/sync': typeof AppSyncRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/content/calendar': typeof AppContentCalendarRoute
  '/content/posts': typeof AppContentPostsRoute
  '/content/queue': typeof AppContentQueueRoute
  '/inbox/engagement': typeof AppInboxEngagementRoute
  '/inbox/messages': typeof AppInboxMessagesRoute
  '/profile/appearance': typeof AppProfileAppearanceRoute
  '/profile/connections': typeof AppProfileConnectionsRoute
  '/profile/notifications': typeof AppProfileNotificationsRoute
  '/profile/security': typeof AppProfileSecurityRoute
  '/profile/settings': typeof AppProfileSettingsRoute
  '/workspace/api-keys': typeof AppWorkspaceApiKeysRoute
  '/workspace/members': typeof AppWorkspaceMembersRoute
  '/workspace/overview': typeof AppWorkspaceOverviewRoute
  '/workspace/subscription': typeof AppWorkspaceSubscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AppAccountsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/sync': typeof AppSyncRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/content/calendar': typeof AppContentCalendarRoute
  '/content/posts': typeof AppContentPostsRoute
  '/content/queue': typeof AppContentQueueRoute
  '/inbox/engagement': typeof AppInboxEngagementRoute
  '/inbox/messages': typeof AppInboxMessagesRoute
  '/profile/appearance': typeof AppProfileAppearanceRoute
  '/profile/connections': typeof AppProfileConnectionsRoute
  '/profile/notifications': typeof AppProfileNotificationsRoute
  '/profile/security': typeof AppProfileSecurityRoute
  '/profile/settings': typeof AppProfileSettingsRoute
  '/workspace/api-keys': typeof AppWorkspaceApiKeysRoute
  '/workspace/members': typeof AppWorkspaceMembersRoute
  '/workspace/overview': typeof AppWorkspaceOverviewRoute
  '/workspace/subscription': typeof AppWorkspaceSubscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/sync': typeof AppSyncRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/two-factor': typeof AuthTwoFactorRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_app/content/calendar': typeof AppContentCalendarRoute
  '/_app/content/posts': typeof AppContentPostsRoute
  '/_app/content/queue': typeof AppContentQueueRoute
  '/_app/inbox/engagement': typeof AppInboxEngagementRoute
  '/_app/inbox/messages': typeof AppInboxMessagesRoute
  '/_app/profile/appearance': typeof AppProfileAppearanceRoute
  '/_app/profile/connections': typeof AppProfileConnectionsRoute
  '/_app/profile/notifications': typeof AppProfileNotificationsRoute
  '/_app/profile/security': typeof AppProfileSecurityRoute
  '/_app/profile/settings': typeof AppProfileSettingsRoute
  '/_app/workspace/api-keys': typeof AppWorkspaceApiKeysRoute
  '/_app/workspace/members': typeof AppWorkspaceMembersRoute
  '/_app/workspace/overview': typeof AppWorkspaceOverviewRoute
  '/_app/workspace/subscription': typeof AppWorkspaceSubscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/analytics'
    | '/dashboard'
    | '/sync'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/two-factor'
    | '/verify-email'
    | '/content/calendar'
    | '/content/posts'
    | '/content/queue'
    | '/inbox/engagement'
    | '/inbox/messages'
    | '/profile/appearance'
    | '/profile/connections'
    | '/profile/notifications'
    | '/profile/security'
    | '/profile/settings'
    | '/workspace/api-keys'
    | '/workspace/members'
    | '/workspace/overview'
    | '/workspace/subscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/analytics'
    | '/dashboard'
    | '/sync'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/two-factor'
    | '/verify-email'
    | '/content/calendar'
    | '/content/posts'
    | '/content/queue'
    | '/inbox/engagement'
    | '/inbox/messages'
    | '/profile/appearance'
    | '/profile/connections'
    | '/profile/notifications'
    | '/profile/security'
    | '/profile/settings'
    | '/workspace/api-keys'
    | '/workspace/members'
    | '/workspace/overview'
    | '/workspace/subscription'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/accounts'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/sync'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/two-factor'
    | '/_auth/verify-email'
    | '/_app/content/calendar'
    | '/_app/content/posts'
    | '/_app/content/queue'
    | '/_app/inbox/engagement'
    | '/_app/inbox/messages'
    | '/_app/profile/appearance'
    | '/_app/profile/connections'
    | '/_app/profile/notifications'
    | '/_app/profile/security'
    | '/_app/profile/settings'
    | '/_app/workspace/api-keys'
    | '/_app/workspace/members'
    | '/_app/workspace/overview'
    | '/_app/workspace/subscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sync': {
      id: '/_app/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AppSyncRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/two-factor': {
      id: '/_auth/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/content/calendar': {
      id: '/_app/content/calendar'
      path: '/content/calendar'
      fullPath: '/content/calendar'
      preLoaderRoute: typeof AppContentCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/posts': {
      id: '/_app/content/posts'
      path: '/content/posts'
      fullPath: '/content/posts'
      preLoaderRoute: typeof AppContentPostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/queue': {
      id: '/_app/content/queue'
      path: '/content/queue'
      fullPath: '/content/queue'
      preLoaderRoute: typeof AppContentQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox/engagement': {
      id: '/_app/inbox/engagement'
      path: '/inbox/engagement'
      fullPath: '/inbox/engagement'
      preLoaderRoute: typeof AppInboxEngagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox/messages': {
      id: '/_app/inbox/messages'
      path: '/inbox/messages'
      fullPath: '/inbox/messages'
      preLoaderRoute: typeof AppInboxMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/appearance': {
      id: '/_app/profile/appearance'
      path: '/profile/appearance'
      fullPath: '/profile/appearance'
      preLoaderRoute: typeof AppProfileAppearanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/connections': {
      id: '/_app/profile/connections'
      path: '/profile/connections'
      fullPath: '/profile/connections'
      preLoaderRoute: typeof AppProfileConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/notifications': {
      id: '/_app/profile/notifications'
      path: '/profile/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof AppProfileNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/security': {
      id: '/_app/profile/security'
      path: '/profile/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof AppProfileSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/settings': {
      id: '/_app/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof AppProfileSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/api-keys': {
      id: '/_app/workspace/api-keys'
      path: '/workspace/api-keys'
      fullPath: '/workspace/api-keys'
      preLoaderRoute: typeof AppWorkspaceApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/members': {
      id: '/_app/workspace/members'
      path: '/workspace/members'
      fullPath: '/workspace/members'
      preLoaderRoute: typeof AppWorkspaceMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/overview': {
      id: '/_app/workspace/overview'
      path: '/workspace/overview'
      fullPath: '/workspace/overview'
      preLoaderRoute: typeof AppWorkspaceOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/subscription': {
      id: '/_app/workspace/subscription'
      path: '/workspace/subscription'
      fullPath: '/workspace/subscription'
      preLoaderRoute: typeof AppWorkspaceSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSyncRoute: typeof AppSyncRoute
  AppContentCalendarRoute: typeof AppContentCalendarRoute
  AppContentPostsRoute: typeof AppContentPostsRoute
  AppContentQueueRoute: typeof AppContentQueueRoute
  AppInboxEngagementRoute: typeof AppInboxEngagementRoute
  AppInboxMessagesRoute: typeof AppInboxMessagesRoute
  AppProfileAppearanceRoute: typeof AppProfileAppearanceRoute
  AppProfileConnectionsRoute: typeof AppProfileConnectionsRoute
  AppProfileNotificationsRoute: typeof AppProfileNotificationsRoute
  AppProfileSecurityRoute: typeof AppProfileSecurityRoute
  AppProfileSettingsRoute: typeof AppProfileSettingsRoute
  AppWorkspaceApiKeysRoute: typeof AppWorkspaceApiKeysRoute
  AppWorkspaceMembersRoute: typeof AppWorkspaceMembersRoute
  AppWorkspaceOverviewRoute: typeof AppWorkspaceOverviewRoute
  AppWorkspaceSubscriptionRoute: typeof AppWorkspaceSubscriptionRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSyncRoute: AppSyncRoute,
  AppContentCalendarRoute: AppContentCalendarRoute,
  AppContentPostsRoute: AppContentPostsRoute,
  AppContentQueueRoute: AppContentQueueRoute,
  AppInboxEngagementRoute: AppInboxEngagementRoute,
  AppInboxMessagesRoute: AppInboxMessagesRoute,
  AppProfileAppearanceRoute: AppProfileAppearanceRoute,
  AppProfileConnectionsRoute: AppProfileConnectionsRoute,
  AppProfileNotificationsRoute: AppProfileNotificationsRoute,
  AppProfileSecurityRoute: AppProfileSecurityRoute,
  AppProfileSettingsRoute: AppProfileSettingsRoute,
  AppWorkspaceApiKeysRoute: AppWorkspaceApiKeysRoute,
  AppWorkspaceMembersRoute: AppWorkspaceMembersRoute,
  AppWorkspaceOverviewRoute: AppWorkspaceOverviewRoute,
  AppWorkspaceSubscriptionRoute: AppWorkspaceSubscriptionRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
