/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSyncRouteImport } from './routes/_app/sync'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthTwoFactorRouteImport } from './routes/_auth/two-factor'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AppContentCalendarRouteImport } from './routes/_app/content/calendar'
import { Route as AppContentPostsRouteImport } from './routes/_app/content/posts'
import { Route as AppContentQueueRouteImport } from './routes/_app/content/queue'
import { Route as AppInboxEngagementRouteImport } from './routes/_app/inbox/engagement'
import { Route as AppInboxMessagesRouteImport } from './routes/_app/inbox/messages'
import { Route as AppProfileNotificationsRouteImport } from './routes/_app/profile/notifications'
import { Route as AppProfileSecurityRouteImport } from './routes/_app/profile/security'
import { Route as AppProfileSettingsRouteImport } from './routes/_app/profile/settings'
import { Route as AppWorkspaceWorkspaceIdRouteImport } from './routes/_app/workspace/$workspaceId'
import { Route as AppWorkspaceWorkspaceIdAccountsRouteImport } from './routes/_app/workspace/$workspaceId/accounts'
import { Route as AppWorkspaceWorkspaceIdAnalyticsRouteImport } from './routes/_app/workspace/$workspaceId/analytics'
import { Route as AppWorkspaceWorkspaceIdApiKeysRouteImport } from './routes/_app/workspace/$workspaceId/api-keys'
import { Route as AppWorkspaceWorkspaceIdDashboardRouteImport } from './routes/_app/workspace/$workspaceId/dashboard'
import { Route as AppWorkspaceWorkspaceIdMembersRouteImport } from './routes/_app/workspace/$workspaceId/members'
import { Route as AppWorkspaceWorkspaceIdOverviewRouteImport } from './routes/_app/workspace/$workspaceId/overview'
import { Route as AppWorkspaceWorkspaceIdSubscriptionRouteImport } from './routes/_app/workspace/$workspaceId/subscription'
import { Route as AppWorkspaceWorkspaceIdSyncRouteImport } from './routes/_app/workspace/$workspaceId/sync'
import { Route as AppWorkspaceWorkspaceIdAnalyticsGrowthRouteImport } from './routes/_app/workspace/$workspaceId/analytics_/growth'
import { Route as AppWorkspaceWorkspaceIdContentCalendarRouteImport } from './routes/_app/workspace/$workspaceId/content/calendar'
import { Route as AppWorkspaceWorkspaceIdContentPostsRouteImport } from './routes/_app/workspace/$workspaceId/content/posts'
import { Route as AppWorkspaceWorkspaceIdContentQueueRouteImport } from './routes/_app/workspace/$workspaceId/content/queue'
import { Route as AppWorkspaceWorkspaceIdInboxEngagementRouteImport } from './routes/_app/workspace/$workspaceId/inbox/engagement'
import { Route as AppWorkspaceWorkspaceIdInboxMessagesRouteImport } from './routes/_app/workspace/$workspaceId/inbox/messages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSyncRoute = AppSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AppContentCalendarRoute = AppContentCalendarRouteImport.update({
  id: '/content/calendar',
  path: '/content/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppContentPostsRoute = AppContentPostsRouteImport.update({
  id: '/content/posts',
  path: '/content/posts',
  getParentRoute: () => AppRoute,
} as any)
const AppContentQueueRoute = AppContentQueueRouteImport.update({
  id: '/content/queue',
  path: '/content/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxEngagementRoute = AppInboxEngagementRouteImport.update({
  id: '/inbox/engagement',
  path: '/inbox/engagement',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxMessagesRoute = AppInboxMessagesRouteImport.update({
  id: '/inbox/messages',
  path: '/inbox/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileNotificationsRoute = AppProfileNotificationsRouteImport.update({
  id: '/profile/notifications',
  path: '/profile/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileSecurityRoute = AppProfileSecurityRouteImport.update({
  id: '/profile/security',
  path: '/profile/security',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileSettingsRoute = AppProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceWorkspaceIdRoute = AppWorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceWorkspaceIdAccountsRoute =
  AppWorkspaceWorkspaceIdAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdAnalyticsRoute =
  AppWorkspaceWorkspaceIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdApiKeysRoute =
  AppWorkspaceWorkspaceIdApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdDashboardRoute =
  AppWorkspaceWorkspaceIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdMembersRoute =
  AppWorkspaceWorkspaceIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdOverviewRoute =
  AppWorkspaceWorkspaceIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdSubscriptionRoute =
  AppWorkspaceWorkspaceIdSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdSyncRoute =
  AppWorkspaceWorkspaceIdSyncRouteImport.update({
    id: '/sync',
    path: '/sync',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdAnalyticsGrowthRoute =
  AppWorkspaceWorkspaceIdAnalyticsGrowthRouteImport.update({
    id: '/analytics_/growth',
    path: '/analytics/growth',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdContentCalendarRoute =
  AppWorkspaceWorkspaceIdContentCalendarRouteImport.update({
    id: '/content/calendar',
    path: '/content/calendar',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdContentPostsRoute =
  AppWorkspaceWorkspaceIdContentPostsRouteImport.update({
    id: '/content/posts',
    path: '/content/posts',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdContentQueueRoute =
  AppWorkspaceWorkspaceIdContentQueueRouteImport.update({
    id: '/content/queue',
    path: '/content/queue',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdInboxEngagementRoute =
  AppWorkspaceWorkspaceIdInboxEngagementRouteImport.update({
    id: '/inbox/engagement',
    path: '/inbox/engagement',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdInboxMessagesRoute =
  AppWorkspaceWorkspaceIdInboxMessagesRouteImport.update({
    id: '/inbox/messages',
    path: '/inbox/messages',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AppAccountsRoute
  '/dashboard': typeof AppDashboardRoute
  '/sync': typeof AppSyncRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/content/calendar': typeof AppContentCalendarRoute
  '/content/posts': typeof AppContentPostsRoute
  '/content/queue': typeof AppContentQueueRoute
  '/inbox/engagement': typeof AppInboxEngagementRoute
  '/inbox/messages': typeof AppInboxMessagesRoute
  '/profile/notifications': typeof AppProfileNotificationsRoute
  '/profile/security': typeof AppProfileSecurityRoute
  '/profile/settings': typeof AppProfileSettingsRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/accounts': typeof AppWorkspaceWorkspaceIdAccountsRoute
  '/workspace/$workspaceId/analytics': typeof AppWorkspaceWorkspaceIdAnalyticsRoute
  '/workspace/$workspaceId/api-keys': typeof AppWorkspaceWorkspaceIdApiKeysRoute
  '/workspace/$workspaceId/dashboard': typeof AppWorkspaceWorkspaceIdDashboardRoute
  '/workspace/$workspaceId/members': typeof AppWorkspaceWorkspaceIdMembersRoute
  '/workspace/$workspaceId/overview': typeof AppWorkspaceWorkspaceIdOverviewRoute
  '/workspace/$workspaceId/subscription': typeof AppWorkspaceWorkspaceIdSubscriptionRoute
  '/workspace/$workspaceId/sync': typeof AppWorkspaceWorkspaceIdSyncRoute
  '/workspace/$workspaceId/analytics/growth': typeof AppWorkspaceWorkspaceIdAnalyticsGrowthRoute
  '/workspace/$workspaceId/content/calendar': typeof AppWorkspaceWorkspaceIdContentCalendarRoute
  '/workspace/$workspaceId/content/posts': typeof AppWorkspaceWorkspaceIdContentPostsRoute
  '/workspace/$workspaceId/content/queue': typeof AppWorkspaceWorkspaceIdContentQueueRoute
  '/workspace/$workspaceId/inbox/engagement': typeof AppWorkspaceWorkspaceIdInboxEngagementRoute
  '/workspace/$workspaceId/inbox/messages': typeof AppWorkspaceWorkspaceIdInboxMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AppAccountsRoute
  '/dashboard': typeof AppDashboardRoute
  '/sync': typeof AppSyncRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/content/calendar': typeof AppContentCalendarRoute
  '/content/posts': typeof AppContentPostsRoute
  '/content/queue': typeof AppContentQueueRoute
  '/inbox/engagement': typeof AppInboxEngagementRoute
  '/inbox/messages': typeof AppInboxMessagesRoute
  '/profile/notifications': typeof AppProfileNotificationsRoute
  '/profile/security': typeof AppProfileSecurityRoute
  '/profile/settings': typeof AppProfileSettingsRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/accounts': typeof AppWorkspaceWorkspaceIdAccountsRoute
  '/workspace/$workspaceId/analytics': typeof AppWorkspaceWorkspaceIdAnalyticsRoute
  '/workspace/$workspaceId/api-keys': typeof AppWorkspaceWorkspaceIdApiKeysRoute
  '/workspace/$workspaceId/dashboard': typeof AppWorkspaceWorkspaceIdDashboardRoute
  '/workspace/$workspaceId/members': typeof AppWorkspaceWorkspaceIdMembersRoute
  '/workspace/$workspaceId/overview': typeof AppWorkspaceWorkspaceIdOverviewRoute
  '/workspace/$workspaceId/subscription': typeof AppWorkspaceWorkspaceIdSubscriptionRoute
  '/workspace/$workspaceId/sync': typeof AppWorkspaceWorkspaceIdSyncRoute
  '/workspace/$workspaceId/analytics/growth': typeof AppWorkspaceWorkspaceIdAnalyticsGrowthRoute
  '/workspace/$workspaceId/content/calendar': typeof AppWorkspaceWorkspaceIdContentCalendarRoute
  '/workspace/$workspaceId/content/posts': typeof AppWorkspaceWorkspaceIdContentPostsRoute
  '/workspace/$workspaceId/content/queue': typeof AppWorkspaceWorkspaceIdContentQueueRoute
  '/workspace/$workspaceId/inbox/engagement': typeof AppWorkspaceWorkspaceIdInboxEngagementRoute
  '/workspace/$workspaceId/inbox/messages': typeof AppWorkspaceWorkspaceIdInboxMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/sync': typeof AppSyncRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/two-factor': typeof AuthTwoFactorRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_app/content/calendar': typeof AppContentCalendarRoute
  '/_app/content/posts': typeof AppContentPostsRoute
  '/_app/content/queue': typeof AppContentQueueRoute
  '/_app/inbox/engagement': typeof AppInboxEngagementRoute
  '/_app/inbox/messages': typeof AppInboxMessagesRoute
  '/_app/profile/notifications': typeof AppProfileNotificationsRoute
  '/_app/profile/security': typeof AppProfileSecurityRoute
  '/_app/profile/settings': typeof AppProfileSettingsRoute
  '/_app/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRouteWithChildren
  '/_app/workspace/$workspaceId/accounts': typeof AppWorkspaceWorkspaceIdAccountsRoute
  '/_app/workspace/$workspaceId/analytics': typeof AppWorkspaceWorkspaceIdAnalyticsRoute
  '/_app/workspace/$workspaceId/api-keys': typeof AppWorkspaceWorkspaceIdApiKeysRoute
  '/_app/workspace/$workspaceId/dashboard': typeof AppWorkspaceWorkspaceIdDashboardRoute
  '/_app/workspace/$workspaceId/members': typeof AppWorkspaceWorkspaceIdMembersRoute
  '/_app/workspace/$workspaceId/overview': typeof AppWorkspaceWorkspaceIdOverviewRoute
  '/_app/workspace/$workspaceId/subscription': typeof AppWorkspaceWorkspaceIdSubscriptionRoute
  '/_app/workspace/$workspaceId/sync': typeof AppWorkspaceWorkspaceIdSyncRoute
  '/_app/workspace/$workspaceId/analytics_/growth': typeof AppWorkspaceWorkspaceIdAnalyticsGrowthRoute
  '/_app/workspace/$workspaceId/content/calendar': typeof AppWorkspaceWorkspaceIdContentCalendarRoute
  '/_app/workspace/$workspaceId/content/posts': typeof AppWorkspaceWorkspaceIdContentPostsRoute
  '/_app/workspace/$workspaceId/content/queue': typeof AppWorkspaceWorkspaceIdContentQueueRoute
  '/_app/workspace/$workspaceId/inbox/engagement': typeof AppWorkspaceWorkspaceIdInboxEngagementRoute
  '/_app/workspace/$workspaceId/inbox/messages': typeof AppWorkspaceWorkspaceIdInboxMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/dashboard'
    | '/sync'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/two-factor'
    | '/verify-email'
    | '/content/calendar'
    | '/content/posts'
    | '/content/queue'
    | '/inbox/engagement'
    | '/inbox/messages'
    | '/profile/notifications'
    | '/profile/security'
    | '/profile/settings'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/accounts'
    | '/workspace/$workspaceId/analytics'
    | '/workspace/$workspaceId/api-keys'
    | '/workspace/$workspaceId/dashboard'
    | '/workspace/$workspaceId/members'
    | '/workspace/$workspaceId/overview'
    | '/workspace/$workspaceId/subscription'
    | '/workspace/$workspaceId/sync'
    | '/workspace/$workspaceId/analytics/growth'
    | '/workspace/$workspaceId/content/calendar'
    | '/workspace/$workspaceId/content/posts'
    | '/workspace/$workspaceId/content/queue'
    | '/workspace/$workspaceId/inbox/engagement'
    | '/workspace/$workspaceId/inbox/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/dashboard'
    | '/sync'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/two-factor'
    | '/verify-email'
    | '/content/calendar'
    | '/content/posts'
    | '/content/queue'
    | '/inbox/engagement'
    | '/inbox/messages'
    | '/profile/notifications'
    | '/profile/security'
    | '/profile/settings'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/accounts'
    | '/workspace/$workspaceId/analytics'
    | '/workspace/$workspaceId/api-keys'
    | '/workspace/$workspaceId/dashboard'
    | '/workspace/$workspaceId/members'
    | '/workspace/$workspaceId/overview'
    | '/workspace/$workspaceId/subscription'
    | '/workspace/$workspaceId/sync'
    | '/workspace/$workspaceId/analytics/growth'
    | '/workspace/$workspaceId/content/calendar'
    | '/workspace/$workspaceId/content/posts'
    | '/workspace/$workspaceId/content/queue'
    | '/workspace/$workspaceId/inbox/engagement'
    | '/workspace/$workspaceId/inbox/messages'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/accounts'
    | '/_app/dashboard'
    | '/_app/sync'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/two-factor'
    | '/_auth/verify-email'
    | '/_app/content/calendar'
    | '/_app/content/posts'
    | '/_app/content/queue'
    | '/_app/inbox/engagement'
    | '/_app/inbox/messages'
    | '/_app/profile/notifications'
    | '/_app/profile/security'
    | '/_app/profile/settings'
    | '/_app/workspace/$workspaceId'
    | '/_app/workspace/$workspaceId/accounts'
    | '/_app/workspace/$workspaceId/analytics'
    | '/_app/workspace/$workspaceId/api-keys'
    | '/_app/workspace/$workspaceId/dashboard'
    | '/_app/workspace/$workspaceId/members'
    | '/_app/workspace/$workspaceId/overview'
    | '/_app/workspace/$workspaceId/subscription'
    | '/_app/workspace/$workspaceId/sync'
    | '/_app/workspace/$workspaceId/analytics_/growth'
    | '/_app/workspace/$workspaceId/content/calendar'
    | '/_app/workspace/$workspaceId/content/posts'
    | '/_app/workspace/$workspaceId/content/queue'
    | '/_app/workspace/$workspaceId/inbox/engagement'
    | '/_app/workspace/$workspaceId/inbox/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sync': {
      id: '/_app/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AppSyncRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/two-factor': {
      id: '/_auth/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/content/calendar': {
      id: '/_app/content/calendar'
      path: '/content/calendar'
      fullPath: '/content/calendar'
      preLoaderRoute: typeof AppContentCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/posts': {
      id: '/_app/content/posts'
      path: '/content/posts'
      fullPath: '/content/posts'
      preLoaderRoute: typeof AppContentPostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/queue': {
      id: '/_app/content/queue'
      path: '/content/queue'
      fullPath: '/content/queue'
      preLoaderRoute: typeof AppContentQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox/engagement': {
      id: '/_app/inbox/engagement'
      path: '/inbox/engagement'
      fullPath: '/inbox/engagement'
      preLoaderRoute: typeof AppInboxEngagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox/messages': {
      id: '/_app/inbox/messages'
      path: '/inbox/messages'
      fullPath: '/inbox/messages'
      preLoaderRoute: typeof AppInboxMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/notifications': {
      id: '/_app/profile/notifications'
      path: '/profile/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof AppProfileNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/security': {
      id: '/_app/profile/security'
      path: '/profile/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof AppProfileSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/settings': {
      id: '/_app/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof AppProfileSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId': {
      id: '/_app/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/accounts': {
      id: '/_app/workspace/$workspaceId/accounts'
      path: '/accounts'
      fullPath: '/workspace/$workspaceId/accounts'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdAccountsRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/analytics': {
      id: '/_app/workspace/$workspaceId/analytics'
      path: '/analytics'
      fullPath: '/workspace/$workspaceId/analytics'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdAnalyticsRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/api-keys': {
      id: '/_app/workspace/$workspaceId/api-keys'
      path: '/api-keys'
      fullPath: '/workspace/$workspaceId/api-keys'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdApiKeysRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/dashboard': {
      id: '/_app/workspace/$workspaceId/dashboard'
      path: '/dashboard'
      fullPath: '/workspace/$workspaceId/dashboard'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdDashboardRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/members': {
      id: '/_app/workspace/$workspaceId/members'
      path: '/members'
      fullPath: '/workspace/$workspaceId/members'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdMembersRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/overview': {
      id: '/_app/workspace/$workspaceId/overview'
      path: '/overview'
      fullPath: '/workspace/$workspaceId/overview'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdOverviewRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/subscription': {
      id: '/_app/workspace/$workspaceId/subscription'
      path: '/subscription'
      fullPath: '/workspace/$workspaceId/subscription'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdSubscriptionRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/sync': {
      id: '/_app/workspace/$workspaceId/sync'
      path: '/sync'
      fullPath: '/workspace/$workspaceId/sync'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdSyncRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/analytics_/growth': {
      id: '/_app/workspace/$workspaceId/analytics_/growth'
      path: '/analytics/growth'
      fullPath: '/workspace/$workspaceId/analytics/growth'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdAnalyticsGrowthRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/content/calendar': {
      id: '/_app/workspace/$workspaceId/content/calendar'
      path: '/content/calendar'
      fullPath: '/workspace/$workspaceId/content/calendar'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdContentCalendarRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/content/posts': {
      id: '/_app/workspace/$workspaceId/content/posts'
      path: '/content/posts'
      fullPath: '/workspace/$workspaceId/content/posts'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdContentPostsRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/content/queue': {
      id: '/_app/workspace/$workspaceId/content/queue'
      path: '/content/queue'
      fullPath: '/workspace/$workspaceId/content/queue'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdContentQueueRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/inbox/engagement': {
      id: '/_app/workspace/$workspaceId/inbox/engagement'
      path: '/inbox/engagement'
      fullPath: '/workspace/$workspaceId/inbox/engagement'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdInboxEngagementRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/inbox/messages': {
      id: '/_app/workspace/$workspaceId/inbox/messages'
      path: '/inbox/messages'
      fullPath: '/workspace/$workspaceId/inbox/messages'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdInboxMessagesRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
  }
}

interface AppWorkspaceWorkspaceIdRouteChildren {
  AppWorkspaceWorkspaceIdAccountsRoute: typeof AppWorkspaceWorkspaceIdAccountsRoute
  AppWorkspaceWorkspaceIdAnalyticsRoute: typeof AppWorkspaceWorkspaceIdAnalyticsRoute
  AppWorkspaceWorkspaceIdApiKeysRoute: typeof AppWorkspaceWorkspaceIdApiKeysRoute
  AppWorkspaceWorkspaceIdDashboardRoute: typeof AppWorkspaceWorkspaceIdDashboardRoute
  AppWorkspaceWorkspaceIdMembersRoute: typeof AppWorkspaceWorkspaceIdMembersRoute
  AppWorkspaceWorkspaceIdOverviewRoute: typeof AppWorkspaceWorkspaceIdOverviewRoute
  AppWorkspaceWorkspaceIdSubscriptionRoute: typeof AppWorkspaceWorkspaceIdSubscriptionRoute
  AppWorkspaceWorkspaceIdSyncRoute: typeof AppWorkspaceWorkspaceIdSyncRoute
  AppWorkspaceWorkspaceIdAnalyticsGrowthRoute: typeof AppWorkspaceWorkspaceIdAnalyticsGrowthRoute
  AppWorkspaceWorkspaceIdContentCalendarRoute: typeof AppWorkspaceWorkspaceIdContentCalendarRoute
  AppWorkspaceWorkspaceIdContentPostsRoute: typeof AppWorkspaceWorkspaceIdContentPostsRoute
  AppWorkspaceWorkspaceIdContentQueueRoute: typeof AppWorkspaceWorkspaceIdContentQueueRoute
  AppWorkspaceWorkspaceIdInboxEngagementRoute: typeof AppWorkspaceWorkspaceIdInboxEngagementRoute
  AppWorkspaceWorkspaceIdInboxMessagesRoute: typeof AppWorkspaceWorkspaceIdInboxMessagesRoute
}

const AppWorkspaceWorkspaceIdRouteChildren: AppWorkspaceWorkspaceIdRouteChildren =
  {
    AppWorkspaceWorkspaceIdAccountsRoute: AppWorkspaceWorkspaceIdAccountsRoute,
    AppWorkspaceWorkspaceIdAnalyticsRoute:
      AppWorkspaceWorkspaceIdAnalyticsRoute,
    AppWorkspaceWorkspaceIdApiKeysRoute: AppWorkspaceWorkspaceIdApiKeysRoute,
    AppWorkspaceWorkspaceIdDashboardRoute:
      AppWorkspaceWorkspaceIdDashboardRoute,
    AppWorkspaceWorkspaceIdMembersRoute: AppWorkspaceWorkspaceIdMembersRoute,
    AppWorkspaceWorkspaceIdOverviewRoute: AppWorkspaceWorkspaceIdOverviewRoute,
    AppWorkspaceWorkspaceIdSubscriptionRoute:
      AppWorkspaceWorkspaceIdSubscriptionRoute,
    AppWorkspaceWorkspaceIdSyncRoute: AppWorkspaceWorkspaceIdSyncRoute,
    AppWorkspaceWorkspaceIdAnalyticsGrowthRoute:
      AppWorkspaceWorkspaceIdAnalyticsGrowthRoute,
    AppWorkspaceWorkspaceIdContentCalendarRoute:
      AppWorkspaceWorkspaceIdContentCalendarRoute,
    AppWorkspaceWorkspaceIdContentPostsRoute:
      AppWorkspaceWorkspaceIdContentPostsRoute,
    AppWorkspaceWorkspaceIdContentQueueRoute:
      AppWorkspaceWorkspaceIdContentQueueRoute,
    AppWorkspaceWorkspaceIdInboxEngagementRoute:
      AppWorkspaceWorkspaceIdInboxEngagementRoute,
    AppWorkspaceWorkspaceIdInboxMessagesRoute:
      AppWorkspaceWorkspaceIdInboxMessagesRoute,
  }

const AppWorkspaceWorkspaceIdRouteWithChildren =
  AppWorkspaceWorkspaceIdRoute._addFileChildren(
    AppWorkspaceWorkspaceIdRouteChildren,
  )

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSyncRoute: typeof AppSyncRoute
  AppContentCalendarRoute: typeof AppContentCalendarRoute
  AppContentPostsRoute: typeof AppContentPostsRoute
  AppContentQueueRoute: typeof AppContentQueueRoute
  AppInboxEngagementRoute: typeof AppInboxEngagementRoute
  AppInboxMessagesRoute: typeof AppInboxMessagesRoute
  AppProfileNotificationsRoute: typeof AppProfileNotificationsRoute
  AppProfileSecurityRoute: typeof AppProfileSecurityRoute
  AppProfileSettingsRoute: typeof AppProfileSettingsRoute
  AppWorkspaceWorkspaceIdRoute: typeof AppWorkspaceWorkspaceIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSyncRoute: AppSyncRoute,
  AppContentCalendarRoute: AppContentCalendarRoute,
  AppContentPostsRoute: AppContentPostsRoute,
  AppContentQueueRoute: AppContentQueueRoute,
  AppInboxEngagementRoute: AppInboxEngagementRoute,
  AppInboxMessagesRoute: AppInboxMessagesRoute,
  AppProfileNotificationsRoute: AppProfileNotificationsRoute,
  AppProfileSecurityRoute: AppProfileSecurityRoute,
  AppProfileSettingsRoute: AppProfileSettingsRoute,
  AppWorkspaceWorkspaceIdRoute: AppWorkspaceWorkspaceIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
